title: Club de Go Nantes Yosakura
description: "Site internet du club de Go Nantes Yosakura."
baseurl: ""
url: "https://nantes.jeudego.org"

markdown: kramdown
plugins:
  - jemoji
theme: minima
permalink: pretty
show_excerpts: True
excerpt_separator: <!--more-->
